### PR TITLE
Customcss

### PR DESCRIPTION
**Pull request by unamaria**
@sharnik 
Here User has a styles attribute and styles change accordingly for the current user. Of course what I want is for everybody to see a user's content accordingly to that attribute regardless of who's logged in, but I'm not sure how.

I guess I could create a method in the ApplicationController that checked the main route (/:handle) and overwrite styles depending on the styles attribute of that handle's owner but it gets messy because all other routes are created with resources and the handle is stored in :user_id. Then should I create routes manually?

I'm sure there's a better approach! :shipit:

### CODE REVIEW

**Comment by sharnik** [comment]
Do you want to overwrite styles for the whole application (incluging user's preference panel) or just for his blog?

In the first case only the current_user would see the colors. In the second case, everybody would see them, buto only when requesting posts_controller#index/#show.

**Comment by unamaria** [comment]
For his blog but it's not just the index blog items view, also views per types of items and show item that belong to different controllers. Mmm... I'll keep investigating.

**Comment by sharnik** [comment]
Only PostItems are displayed natively (in your app), the rest redirects to external services. I'd say it's just a few actions that would use the custom look.

**Comment by unamaria** [comment]
I was imagining all views that display content and someone other that the owner can see should use the custom look (post_items/medium_items#show, blog_items/post_items/medium_items/flickr_items#index) (now it's possible to edit a medium post for example, so it can grow apart from the original one and it has a show action -also, in index I just display an excerpt. I thought it should be possible too to list items from one category. Maybe I should rethink this?).

But even if it was just one I haven't found a good solution, for using content_for doesn't work properly (I think) because stylesheets are cached.

**Comment by sharnik** [comment]
It's actually a good idea with displaying all the posts in your app, I didn't think about it. It's cool.

The stylesheets will normally be cached by browser, but when you do a hard refresh (cmd + r) it works?

**Comment by unamaria** [comment]
Yes, that's it!

**Pull request merged**
